export const ActionType={
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCREMENT_QUANTITY:"INCREMENT_QUANTITY",
    DECREMENT_QUANTITY:"DECREMENT_QUANTITY",
    LOGIN_USER:"LOGIN_USER",
    LOGOUT_USER:"LOGOUT_USER"
};